version: '3'

services:
  web:
    build: .
    command: /code/manage.py runserver 0:8000
    tty: True
    volumes:
    - web-static:/code/.deployment/static
    expose:
    - "8000"
  static:
    restart: always
    build: .deployment/nginx/
    volumes:
    - web-static:/usr/share/nginx/static

volumes:
  web-static: